In [1]:
import numpy as np
import pandas as pd

In [23]:
jobs_df = pd.read_csv("data/jobs.csv")

In [24]:
skills_df=pd.read_csv("data/skills_combined.csv")

In [25]:
jobs_df.shape

(50, 8)

In [26]:
skills_df.shape

(151, 2)

In [11]:
jobs_df = jobs_df.drop_duplicates()

In [13]:
jobs_df["job_id"].nunique()

51

In [14]:
jobs_df[jobs_df.duplicated(subset=["job_id"], keep=False)]

Empty DataFrame
Columns: [job_id, company_name, role, location, job_description, required_skills, preferred_skills, experience_req]
Index: []

In [15]:
jobs_df.tail(5)

,job_id,company_name,role,location,job_description,required_skills,preferred_skills,experience_req
47,JOB048,Concentrix,Business Analyst – Fresher (Analytics Operations),"Bengaluru, Karnataka",Concentrix is hiring fresh Business Analysts f...,"MS Excel, Communication Skills, Requirement An...","SQL, Power BI, JIRA, Agile, PowerPoint",0 – 1 Year (Freshers)
48,JOB049,Oracle India,Junior Software Developer – Cloud Applications,"Hyderabad, Telangana",Oracle India is hiring Junior Software Develop...,"Core Java, OOP Concepts, SQL, DSA, Problem Sol...","Spring Framework, REST APIs, Oracle DB, Git, A...",0 – 1 Year (Freshers)
49,JOB050,Nagarro,Associate Engineer – Data & Analytics,"Pune, Maharashtra",Nagarro is hiring Associate Engineers for its ...,"Python (Pandas), SQL, Power BI, OOP, Analytica...","DAX, Power Query, Azure Data Factory basics, G...",0 – 1 Year (Freshers)
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,job_id,company_name,role,location,job_description,required_skills,preferred_skills,experience_req

In [16]:
jobs_df = jobs_df.dropna(how='all')

In [17]:
jobs_df = jobs_df[jobs_df["job_id"] != "job_id"]

In [19]:
jobs_df["job_id"].nunique()

50

In [21]:
jobs_df.to_csv("data/jobs.csv",index=False)

In [22]:
jobs_df.shape

(50, 8)

In [27]:
skill_lookup=dict(
    zip(skills_df['skill_name'],skills_df['skill_id'])
)

In [28]:
job_skills=[]

In [30]:
for _,row in jobs_df.iterrows():
    job_id=row['job_id']

    required_skills= row['required_skills'].split(',')

    for skill in required_skills:
        skill=skill.strip()

        if skill in skill_lookup:
            job_skills.append([
                job_id,
                skill_lookup[skill],
                "Required"
            ])

In [33]:
for _,row in jobs_df.iterrows():
    job_id=row['job_id']

    preferred_skills= row["preferred_skills"].split(",")
    for skill in preferred_skills:
        skill=skill.strip()

        if skill in skill_lookup:
            job_skills.append([
                job_id,
                skill_lookup[skill],
                "Preferred"
            ])

In [34]:
job_skills_df = pd.DataFrame(
    job_skills,
    columns=[
        "job_id",
        "skill_id",
        "skill_type"
    ]
)

In [35]:
job_skills_df.head()

   job_id  skill_id skill_type
0  JOB001        73   Required
1  JOB001       111   Required
2  JOB001        97   Required
3  JOB001        22   Required
4  JOB001        81   Required

In [36]:
job_skills_df.shape

(500, 3)

In [41]:
job_skills_df.to_csv("data/job_skills.csv",index=False)

In [38]:
job_skills_df.tail()

     job_id  skill_id skill_type
495  JOB050        38  Preferred
496  JOB050       106  Preferred
497  JOB050        12  Preferred
498  JOB050        62  Preferred
499  JOB050       134  Preferred