In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv("../data/jobs.csv")

In [16]:
df.head()

,job_id,company_name,role,location,job_description,required_skills,preferred_skills,experience_req
0,JOB001,Tata Consultancy Services (TCS),System Engineer,"Chennai, Tamil Nadu",TCS is hiring System Engineers under its NQT N...,"Java, Python, OOP Concepts, Basic SQL, Logical...","Data Structures & Algorithms, Git, Linux Basic...",0 – 1 Year (Freshers)
1,JOB002,Infosys,System Engineer,"Bengaluru, Karnataka",Infosys is hiring System Engineers through its...,"Core Java, Python, SQL, OOP, Problem Solving, ...","Spring Framework, Hibernate, REST APIs, Git",0 – 1 Year (Freshers)
2,JOB003,Wipro,Project Engineer,"Pune, Maharashtra",Wipro's NLTH (National Level Talent Hunt) trac...,"Core Java, SQL, OOP, Data Structures, Verbal C...","Selenium, Maven, Spring Boot, Linux, Git",0 – 1 Year (Freshers)
3,JOB004,Cognizant Technology Solutions,Graduate Trainee – Software Engineer,"Hyderabad, Telangana",Cognizant's GenC (Generation Cognizant) progra...,"Core Java or Python, SQL, OOP Principles, Basi...","Angular/React basics, REST APIs, Git, JIRA",0 – 1 Year (Freshers)
4,JOB005,HCL Technologies,Graduate Engineer Trainee,"Noida, Uttar Pradesh",HCLTech Mega Off Campus Drive 2026 is hiring G...,"Java or C++, SQL, OOP, Computer Networks, Anal...","Cloud Fundamentals (AWS/Azure basics), Linux, ...",0 – 1 Year (Freshers)

In [17]:
df.shape

(50, 8)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            50 non-null     object
 1   company_name      50 non-null     object
 2   role              50 non-null     object
 3   location          50 non-null     object
 4   job_description   50 non-null     object
 5   required_skills   50 non-null     object
 6   preferred_skills  50 non-null     object
 7   experience_req    50 non-null     object
dtypes: object(8)
memory usage: 3.3+ KB

In [19]:
df.columns

Index(['job_id', 'company_name', 'role', 'location', 'job_description',
       'required_skills', 'preferred_skills', 'experience_req'],
      dtype='object')

In [20]:
df["required_skills"].head()

0    Java, Python, OOP Concepts, Basic SQL, Logical...
1    Core Java, Python, SQL, OOP, Problem Solving, ...
2    Core Java, SQL, OOP, Data Structures, Verbal C...
3    Core Java or Python, SQL, OOP Principles, Basi...
4    Java or C++, SQL, OOP, Computer Networks, Anal...
Name: required_skills, dtype: object

In [21]:
df["preferred_skills"].head()

0    Data Structures & Algorithms, Git, Linux Basic...
1          Spring Framework, Hibernate, REST APIs, Git
2             Selenium, Maven, Spring Boot, Linux, Git
3           Angular/React basics, REST APIs, Git, JIRA
4    Cloud Fundamentals (AWS/Azure basics), Linux, ...
Name: preferred_skills, dtype: object

In [22]:
all_skills=[]

In [23]:
for skills in df['required_skills']:
    skills_list=skills.split(',')
    for skills in skills_list:
        all_skills.append(skills.strip())

In [24]:
for skill in df['preferred_skills']:
    skills_lst=skill.split(',')
    for skill in skills_lst:
        all_skills.append(skill.strip())

In [25]:
unique_skills=sorted(set(all_skills))

In [26]:
print("All Unique Skills are: ",unique_skills)

All Unique Skills are:  ['AWS Fundamentals', 'Active Directory', 'Agile', 'Agile Methodology', 'Agile/Scrum', 'Analytical Skills', 'Analytical Thinking', 'Angular/React basics', 'Application Monitoring', 'Application Monitoring Tools', 'Attention to Detail', 'Azure Data Factory basics', 'Azure Data basics', 'Azure Fundamentals', 'BFSI domain awareness', 'Banking Application awareness', 'Banking Domain basics', 'Banking Domain knowledge', 'Basic DSA', 'Basic Networking', 'Basic Networking (TCP/IP', 'Basic SQL', 'Business Analysis', 'Business Communication', 'Charts', 'Charts)', 'Cloud Basics (AWS)', 'Cloud Fundamentals', 'Cloud Fundamentals (AWS/Azure basics)', 'Cloud Fundamentals (AWS/Azure)', 'Cloud basics', 'Communication Skills', 'Communication Skills (English)', 'Computer Networks', 'Confluence', 'Core Java', 'Core Java or Python', 'DAX', 'DBMS', 'DHCP)', 'DNS', 'DNS)', 'DSA', 'DSA basics', 'Data Entry', 'Data Governance basics', 'Data Profiling', 'Data Structures', 'Data Structures & Algorithms', 'Data Validation', 'Data Visualization basics', 'Documentation', 'ERP basics (SAP)', 'ETL basics', 'ETL concepts', 'Excel', 'Excel (Pivot Tables', 'Excel (Pivot Tables)', 'Excel (VLOOKUP', 'Excel (advanced)', 'Flask/FastAPI basics', 'Git', 'Healthcare domain knowledge', 'Hibernate', 'Hypothesis Testing', 'IBM Cloud Pak basics', 'ITIL', 'ITIL Foundation', 'ITSM / Ticketing', 'ITSM Basics', 'Insurance domain awareness', 'JIRA', 'Java', 'Java basics', 'Java or C++', 'Java or Python', 'Jira', 'Linux', 'Linux Basics', 'Linux basics', 'Logical Reasoning', 'MIS Reporting', 'MS Access', 'MS Excel', 'MS Excel (Advanced)', 'MS Excel (Pivot Tables', 'MS Office', 'MS Office 365', 'Machine Learning basics', 'Macros/VBA', 'Matplotlib', 'Matplotlib)', 'Maven', 'Networking Fundamentals', 'NumPy)', 'OOP', 'OOP Concepts', 'OOP Principles', 'Oracle DB', 'Oracle/SAP basics', 'PivotTable', 'Postman', 'Power BI', 'Power BI basics', 'Power BI or Tableau', 'Power Query', 'PowerPoint', 'Probability', 'Problem Solving', 'Process Mapping', 'Python', 'Python (Pandas', 'Python (Pandas)', 'Python basics', 'Python or Java', 'REST API Basics', 'REST APIs', 'React or Angular basics', 'Remote Desktop Tools', 'Requirement Analysis', 'Requirement Gathering', 'SAP awareness', 'SQL', 'SQL basics', 'Seaborn/Matplotlib', 'Selenium', 'ServiceNow', 'Shell Scripting', 'Spark basics', 'Spring Boot', 'Spring Framework', 'Stakeholder Management', 'Statistical Analysis', 'Statistics', 'Statistics basics', 'Tableau', 'Teamwork', 'TestNG', 'Ticketing', 'Ticketing Systems', 'Ticketing Tools', 'Ticketing Tools (ServiceNow / Remedy)', 'Unix/Linux', 'VBA', 'VLOOKUP)', 'VPN troubleshooting', 'Verbal Communication', 'Virtualization basics', 'Visio', 'Windows OS', 'Windows OS Troubleshooting']

In [27]:
print("Total Unique Skills: ",len(unique_skills))

Total Unique Skills:  151

In [29]:
skills_df=pd.DataFrame({
    'skill_id': range(1,len(unique_skills)+1),
    'skill_name' : unique_skills
})

In [30]:
skills_df.head()

   skill_id         skill_name
0         1   AWS Fundamentals
1         2   Active Directory
2         3              Agile
3         4  Agile Methodology
4         5        Agile/Scrum

In [31]:
skills_df.shape

(151, 2)

In [32]:
skills_df.to_csv("../data/skills_combined.csv",index=False)